# Netlify Build Configuration for the Learning Tracker project

[build]
  # The command to build the site
  command = "npm run build"

  # The directory that contains the deploy-ready assets
  publish = "dist"

[secrets]
  scan_omit_keys = ["VITE_SUPABASE_ANON_KEY", "VITE_SUPABASE_URL"]
